// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBsFFAy30NfWbcAmcpWdJvkmeTH6zjXkg',
    appId: '1:95934699604:android:16faa7d37953a7679875c1',
    messagingSenderId: '95934699604',
    projectId: 'scraper-db59b',
    storageBucket: 'scraper-db59b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRepsrYWLwoSCQBTxIlYQPIoDTs8YiyvU',
    appId: '1:95934699604:ios:07d6cf4fa3dba5b29875c1',
    messagingSenderId: '95934699604',
    projectId: 'scraper-db59b',
    storageBucket: 'scraper-db59b.firebasestorage.app',
    iosBundleId: 'com.example.scraper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEXG3UJmeQOp825lQUPGUwHvIoVl30vF8',
    appId: '1:95934699604:web:7321ed303e18182d9875c1',
    messagingSenderId: '95934699604',
    projectId: 'scraper-db59b',
    authDomain: 'scraper-db59b.firebaseapp.com',
    storageBucket: 'scraper-db59b.firebasestorage.app',
    measurementId: 'G-22Y4P8WBMY',
  );

}